-- MySQL Script generated by MySQL Workbench
-- Wed Aug 10 14:03:27 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_buyge
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bd_buyge` ;

-- -----------------------------------------------------
-- Schema bd_buyge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_buyge` DEFAULT CHARACTER SET utf8 ;
USE `bd_buyge` ;

-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_cliente` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_cliente` (
  `cd_cliente` INT NOT NULL AUTO_INCREMENT,
  `nm_cliente` VARCHAR(20) NOT NULL,
  `nm_sobrenome_cliente` VARCHAR(40) NOT NULL,
  `dt_nascimento_cliente` DATE NOT NULL,
  `nm_email_cliente` VARCHAR(30) NOT NULL,
  `nr_telefone` CHAR(11) NOT NULL,
  `nm_login` VARCHAR(30) NOT NULL,
  `nm_senha` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`cd_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_jogador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_jogador` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_jogador` (
  `cd_jogador` INT NOT NULL AUTO_INCREMENT,
  `nr_nivel_jogador` INT NOT NULL,
  `nr_xp_jogador` BIGINT NOT NULL,
  `nm_classe` VARCHAR(20) NOT NULL,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_jogador`, `fk_cd_cliente`),
  INDEX `fk_tb_jogador_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_jogador_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bd_buyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_mercante`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_mercante` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_mercante` (
  `cd_mercante` INT NOT NULL AUTO_INCREMENT,
  `nm_loja_mercante` VARCHAR(30) NOT NULL,
  `ds_loja_mercante` LONGTEXT NOT NULL,
  `img_logo_mercante` BLOB NULL,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_mercante`),
  INDEX `fk_tb_loja_virtual_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_loja_virtual_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bd_buyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_produto` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_produto` (
  `cd_produto` INT NOT NULL AUTO_INCREMENT,
  `nm_produto` VARCHAR(30) NOT NULL,
  `ds_produto` LONGTEXT NOT NULL,
  `vl_produto` DECIMAL(8,2) NOT NULL,
  `ds_caracteristicas` LONGTEXT NOT NULL,
  `qt_estoque_produto` INT NOT NULL,
  PRIMARY KEY (`cd_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_carrinho` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_carrinho` (
  `cd_carrinho` INT NOT NULL AUTO_INCREMENT,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_carrinho`, `fk_cd_cliente`),
  INDEX `fk_tb_carrinho_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_carrinho_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bd_buyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_item_carrinho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_item_carrinho` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_item_carrinho` (
  `cd_item_carrinho` INT NOT NULL AUTO_INCREMENT,
  `vl_item_carrinho` DECIMAL(8,2) NOT NULL,
  `fk_cd_produto` INT NOT NULL,
  `fk_cd_carrinho` INT NOT NULL,
  PRIMARY KEY (`cd_item_carrinho`),
  INDEX `fk_tb_item_carrinho_tb_produto1_idx` (`fk_cd_produto` ASC) VISIBLE,
  INDEX `fk_tb_item_carrinho_tb_carrinho1_idx` (`fk_cd_carrinho` ASC) VISIBLE,
  CONSTRAINT `fk_tb_item_carrinho_tb_produto1`
    FOREIGN KEY (`fk_cd_produto`)
    REFERENCES `bd_buyge`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_item_carrinho_tb_carrinho1`
    FOREIGN KEY (`fk_cd_carrinho`)
    REFERENCES `bd_buyge`.`tb_carrinho` (`cd_carrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_favorito` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_favorito` (
  `cd_favorito` INT NOT NULL AUTO_INCREMENT,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_favorito`, `fk_cd_cliente`),
  INDEX `fk_tb_favorito_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_favorito_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bd_buyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_item_favorito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_item_favorito` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_item_favorito` (
  `cd_item_favorito` INT NOT NULL AUTO_INCREMENT,
  `fk_cd_favorito` INT NOT NULL,
  `fk_cd_produto` INT NOT NULL,
  PRIMARY KEY (`cd_item_favorito`),
  INDEX `fk_tb_item_favorito_tb_favorito1_idx` (`fk_cd_favorito` ASC) VISIBLE,
  INDEX `fk_tb_item_favorito_tb_produto1_idx` (`fk_cd_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_item_favorito_tb_favorito1`
    FOREIGN KEY (`fk_cd_favorito`)
    REFERENCES `bd_buyge`.`tb_favorito` (`cd_favorito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_item_favorito_tb_produto1`
    FOREIGN KEY (`fk_cd_produto`)
    REFERENCES `bd_buyge`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_endereco` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_endereco` (
  `cd_endereco` INT NOT NULL AUTO_INCREMENT,
  `nm_logradouro_endereco` VARCHAR(30) NOT NULL,
  `nr_endereco` BIGINT NOT NULL,
  `nm_bairro_endereco` VARCHAR(30) NOT NULL,
  `nr_cep_endereco` BIGINT NOT NULL,
  `nm_cidade_endereco` VARCHAR(30) NOT NULL,
  `sg_estado` CHAR(2) NOT NULL,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_endereco`, `fk_cd_cliente`),
  INDEX `fk_tb_endereco_tb_cliente_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_endereco_tb_cliente`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bd_buyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_categoria` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_categoria` (
  `cd_categoria` INT NOT NULL AUTO_INCREMENT,
  `nm_categoria` VARCHAR(30) NOT NULL,
  `ds_categoria` LONGTEXT NOT NULL,
  PRIMARY KEY (`cd_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_produto_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_produto_categoria` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_produto_categoria` (
  `fk_cd_produto` INT NOT NULL,
  `fk_cd_categoria` INT NOT NULL,
  PRIMARY KEY (`fk_cd_produto`, `fk_cd_categoria`),
  INDEX `fk_tb_produto_has_tb_categoria_tb_categoria1_idx` (`fk_cd_categoria` ASC) VISIBLE,
  INDEX `fk_tb_produto_has_tb_categoria_tb_produto1_idx` (`fk_cd_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_has_tb_categoria_tb_produto1`
    FOREIGN KEY (`fk_cd_produto`)
    REFERENCES `bd_buyge`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_has_tb_categoria_tb_categoria1`
    FOREIGN KEY (`fk_cd_categoria`)
    REFERENCES `bd_buyge`.`tb_categoria` (`cd_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_buyge`.`tb_produto_imagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bd_buyge`.`tb_produto_imagem` ;

CREATE TABLE IF NOT EXISTS `bd_buyge`.`tb_produto_imagem` (
  `cd_produto_imagem` INT NOT NULL AUTO_INCREMENT,
  `nm_produto_imagem` VARCHAR(35) NOT NULL,
  `img_produto` BLOB NOT NULL,
  `fk_cd_produto` INT NOT NULL,
  PRIMARY KEY (`cd_produto_imagem`, `fk_cd_produto`),
  INDEX `fk_tb_produto_imagem_tb_produto1_idx` (`fk_cd_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_imagem_tb_produto1`
    FOREIGN KEY (`fk_cd_produto`)
    REFERENCES `bd_buyge`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
