-- MySQL Script generated by MySQL Workbench
-- Fri Oct 14 09:46:08 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdbuyge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdbuyge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdbuyge` DEFAULT CHARACTER SET utf8 ;
USE `bdbuyge` ;

-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_cliente` (
  `cd_cliente` INT NOT NULL AUTO_INCREMENT,
  `nm_cliente` VARCHAR(40) NOT NULL,
  `nm_sobrenome` VARCHAR(60) NOT NULL,
  `dt_nascimento` DATE NOT NULL,
  `nr_telefone` CHAR(11) NOT NULL,
  `nm_login` VARCHAR(30) NOT NULL,
  `nm_senha` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`cd_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_endereco` (
  `cd_endereco` INT NOT NULL AUTO_INCREMENT,
  `nm_logradouro` VARCHAR(30) NOT NULL,
  `nr_endereco` BIGINT NOT NULL,
  `nm_bairro` VARCHAR(30) NOT NULL,
  `nr_cep` CHAR(8) NOT NULL,
  `nm_cidade` VARCHAR(30) NOT NULL,
  `sg_estado` CHAR(2) NOT NULL,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_endereco`),
  INDEX `fk_tb_endereco_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_endereco_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bdbuyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_mercante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_mercante` (
  `cd_mercante` INT NOT NULL AUTO_INCREMENT,
  `nm_loja` VARCHAR(30) NOT NULL,
  `ds_loja` LONGTEXT NOT NULL,
  `img_logo` MEDIUMTEXT NOT NULL,
  `nr_cnpj` CHAR(14) NULL,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_mercante`),
  INDEX `fk_tb_mercante_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_mercante_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bdbuyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_carrinho` (
  `cd_carrinho` INT NOT NULL AUTO_INCREMENT,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_carrinho`),
  INDEX `fk_tb_carrinho_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_carrinho_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bdbuyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_favorito` (
  `cd_favorito` INT NOT NULL AUTO_INCREMENT,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_favorito`),
  INDEX `fk_tb_favorito_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_favorito_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bdbuyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_categoria` (
  `cd_categoria` INT NOT NULL AUTO_INCREMENT,
  `nm_categoria` VARCHAR(30) NOT NULL,
  `ds_categoria` LONGTEXT NOT NULL,
  PRIMARY KEY (`cd_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_produto` (
  `cd_produto` INT NOT NULL AUTO_INCREMENT,
  `nm_produto` VARCHAR(30) NOT NULL,
  `ds_produto` LONGTEXT NOT NULL,
  `vl_produto` DECIMAL(8,2) NOT NULL,
  `qt_produto` INT NOT NULL,
  `fk_cd_mercante` INT NOT NULL,
  `fk_cd_categoria` INT NOT NULL,
  PRIMARY KEY (`cd_produto`),
  INDEX `fk_tb_produto_tb_mercante1_idx` (`fk_cd_mercante` ASC) VISIBLE,
  INDEX `fk_tb_produto_tb_categoria1_idx` (`fk_cd_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_tb_mercante1`
    FOREIGN KEY (`fk_cd_mercante`)
    REFERENCES `bdbuyge`.`tb_mercante` (`cd_mercante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_tb_categoria1`
    FOREIGN KEY (`fk_cd_categoria`)
    REFERENCES `bdbuyge`.`tb_categoria` (`cd_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_produto_imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_produto_imagem` (
  `cd_produto_imagem` INT NOT NULL AUTO_INCREMENT,
  `img_produto` MEDIUMTEXT NOT NULL,
  `ds_imagem_produto` LONGTEXT NOT NULL,
  `fk_cd_produto` INT NOT NULL,
  PRIMARY KEY (`cd_produto_imagem`),
  INDEX `fk_tb_produto_imagem_tb_produto1_idx` (`fk_cd_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_imagem_tb_produto1`
    FOREIGN KEY (`fk_cd_produto`)
    REFERENCES `bdbuyge`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_item_favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_item_favorito` (
  `cd_item_favorito` INT NOT NULL AUTO_INCREMENT,
  `fk_cd_produto` INT NOT NULL,
  `fk_cd_favorito` INT NOT NULL,
  INDEX `fk_tb_produto_has_tb_favorito_tb_favorito1_idx` (`fk_cd_favorito` ASC) VISIBLE,
  INDEX `fk_tb_produto_has_tb_favorito_tb_produto1_idx` (`fk_cd_produto` ASC) VISIBLE,
  PRIMARY KEY (`cd_item_favorito`),
  CONSTRAINT `fk_tb_produto_has_tb_favorito_tb_produto1`
    FOREIGN KEY (`fk_cd_produto`)
    REFERENCES `bdbuyge`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_has_tb_favorito_tb_favorito1`
    FOREIGN KEY (`fk_cd_favorito`)
    REFERENCES `bdbuyge`.`tb_favorito` (`cd_favorito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_item_carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_item_carrinho` (
  `cd_item_carrinho` INT NOT NULL AUTO_INCREMENT,
  `fk_cd_produto` INT NOT NULL,
  `fk_cd_carrinho` INT NOT NULL,
  INDEX `fk_tb_produto_has_tb_carrinho_tb_carrinho1_idx` (`fk_cd_carrinho` ASC) VISIBLE,
  INDEX `fk_tb_produto_has_tb_carrinho_tb_produto1_idx` (`fk_cd_produto` ASC) VISIBLE,
  PRIMARY KEY (`cd_item_carrinho`),
  CONSTRAINT `fk_tb_produto_has_tb_carrinho_tb_produto1`
    FOREIGN KEY (`fk_cd_produto`)
    REFERENCES `bdbuyge`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_has_tb_carrinho_tb_carrinho1`
    FOREIGN KEY (`fk_cd_carrinho`)
    REFERENCES `bdbuyge`.`tb_carrinho` (`cd_carrinho`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_compra` (
  `cd_compra` INT NOT NULL AUTO_INCREMENT,
  `vl_total_compra` DECIMAL(8,2) NOT NULL,
  `fk_cd_cliente` INT NOT NULL,
  PRIMARY KEY (`cd_compra`),
  INDEX `fk_tb_compra_tb_cliente1_idx` (`fk_cd_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_tb_compra_tb_cliente1`
    FOREIGN KEY (`fk_cd_cliente`)
    REFERENCES `bdbuyge`.`tb_cliente` (`cd_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdbuyge`.`tb_item_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdbuyge`.`tb_item_compra` (
  `cd_item_compra` INT NOT NULL AUTO_INCREMENT,
  `vl_item_compra` DECIMAL(8,2) NOT NULL,
  `fk_cd_produto` INT NOT NULL,
  `fk_cd_compra` INT NOT NULL,
  PRIMARY KEY (`cd_item_compra`),
  INDEX `fk_tb_produto_has_tb_compra_tb_compra1_idx` (`fk_cd_compra` ASC) VISIBLE,
  INDEX `fk_tb_produto_has_tb_compra_tb_produto1_idx` (`fk_cd_produto` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produto_has_tb_compra_tb_produto1`
    FOREIGN KEY (`fk_cd_produto`)
    REFERENCES `bdbuyge`.`tb_produto` (`cd_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produto_has_tb_compra_tb_compra1`
    FOREIGN KEY (`fk_cd_compra`)
    REFERENCES `bdbuyge`.`tb_compra` (`cd_compra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
